//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/contract/HelloWorld", ConfigurationName="ServiceReference.HelloWorldPortType")]
    public interface HelloWorldPortType
    {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.example.org/schema/HelloWorld) of message HelloWorldRequest does not match the default value (http://www.example.org/contract/HelloWorld)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/contract/HelloWorld/HelloWorldPortType/HelloWorldRequest", ReplyAction="http://www.example.org/contract/HelloWorld/HelloWorldPortType/HelloWorldResponse")]
        ServiceReference.HelloWorldResponse HelloWorld(ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/contract/HelloWorld/HelloWorldPortType/HelloWorldRequest", ReplyAction="http://www.example.org/contract/HelloWorld/HelloWorldPortType/HelloWorldResponse")]
        System.Threading.Tasks.Task<ServiceReference.HelloWorldResponse> HelloWorldAsync(ServiceReference.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="http://www.example.org/schema/HelloWorld", IsWrapped=true)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string name;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(string name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="http://www.example.org/schema/HelloWorld", IsWrapped=true)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string response;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface HelloWorldPortTypeChannel : ServiceReference.HelloWorldPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class HelloWorldPortTypeClient : System.ServiceModel.ClientBase<ServiceReference.HelloWorldPortType>, ServiceReference.HelloWorldPortType
    {
        
        public HelloWorldPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference.HelloWorldResponse ServiceReference.HelloWorldPortType.HelloWorld(ServiceReference.HelloWorldRequest request)
        {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string name)
        {
            ServiceReference.HelloWorldRequest inValue = new ServiceReference.HelloWorldRequest();
            inValue.name = name;
            ServiceReference.HelloWorldResponse retVal = ((ServiceReference.HelloWorldPortType)(this)).HelloWorld(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.HelloWorldResponse> ServiceReference.HelloWorldPortType.HelloWorldAsync(ServiceReference.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.HelloWorldResponse> HelloWorldAsync(string name)
        {
            ServiceReference.HelloWorldRequest inValue = new ServiceReference.HelloWorldRequest();
            inValue.name = name;
            return ((ServiceReference.HelloWorldPortType)(this)).HelloWorldAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public new virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
